### ISSUE TITLE
Butterfly works as a static blog generator (no posts)

### ISSUE THREAD

**Issue by MatthijsKamstra** [ashes999/butterfly#3]
I was testing butterfly, and I was thinking it would be useful to have a clean project generator.

`butterfly path/to/folder -generate` or something

Currently you need to have a `post` folder, but I wanted to use it only for pages.
This gave an error.
(`Uncaught exception - /path/to/src/posts doesn't exist`)

**Comment by ashes999** [comment]
I'm not sure I understand how this is different from #4.

Let's say I fix #4. Can you clarify what kind of parameters or generator you want?

The way I use it, with DropBox, I have two folders:

```
~/DropBox/learnhaxe
~/DropBox/butterfly
```

From the `butterfly` folder, I invoke `./run.sh ../learnhaxe`. I know this might not be ideal, but it works for me.

What works for you? What changes do you need?

You shouldn't be including posts/pages in your clone of `butterfly` itself.

**Comment by ashes999** [comment]
I've submitted and tested a fix. Please test it on your side, and re-open this issue if the problem persists.

**Comment by ashes999** [comment]
Repurposing this issue: what changes need to go into Butterfly to make it work as a static website generator?

**Comment by MatthijsKamstra** [comment]
It's a feature I had for cybermonk. You could generate a empty/basic `src` with all the necessary folders/files. 
But working on/with Butterfly I realize that it's a really lightweight solution. Not sure if I still feel the same about the generator.

In the description I wrote I shouldn't have mentioned `post` that de-railed the issue.

**Comment by ashes999** [comment]
@MatthijsKamstra I didn't merge any of your changes, but I would like to get your name into the list of contributers. Is it possible you could fork and commit something small (maybe even just a README change or something)?

**Comment by MatthijsKamstra** [comment]
i will try
